#ifndef BOX64_COMPAT_PTHREAD_H
#define BOX64_COMPAT_PTHREAD_H

#include_next <pthread.h>

#if defined(__APPLE__)
#ifndef PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP
#define PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP PTHREAD_MUTEX_INITIALIZER
#endif
#endif

#endif
